auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# Allow logs up to 1 month old
limits_config:
  # Allow logs up to 30 days old
  max_query_lookback: 8766h
  # Increase the rejection window to allow older logs
  reject_old_samples: false
  # Allow ingestion of logs up to 30 days old
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  # Increase the retention period
  retention_period: 8766h

# Increase the ingester limits
ingester:
  # Allow processing of older logs
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s

# Compactor settings for better performance with older logs
compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
