// Grafana Alloy Configuration - Remote Agent
// Collects metrics and logs, forwards to central server

// =============================================================================
// PROMETHEUS METRICS COLLECTION AND FORWARDING
// =============================================================================

// System metrics exporter (local)
prometheus.exporter.unix "local_system" {
  procfs_path = "/host/proc"
  sysfs_path = "/host/sys"
}

// Scrape local system metrics
prometheus.scrape "local_system_metrics" {
  targets         = prometheus.exporter.unix.local_system.targets
  forward_to      = [prometheus.relabel.filter_metrics.receiver]
  scrape_interval = "15s"
}

// Filter and relabel metrics
prometheus.relabel "filter_metrics" {
  rule {
    action        = "keep"
    source_labels = ["__name__"]
    regex         = "(node_.*|process_.*|go_.*)"
  }
  
  rule {
    action        = "replace"
    source_labels = ["__name__"]
    target_label  = "metric_type"
    regex         = "node_(.+)"
    replacement   = "system"
  }

  rule {
    action        = "replace"
    source_labels = ["__address__"]
    target_label  = "instance"
    replacement   = env("HOSTNAME")
  }

  forward_to = [prometheus.remote_write.prometheus_service.receiver]
}

// Write metrics to central Prometheus
prometheus.remote_write "prometheus_service" {
  endpoint {
    url = env("PROMETHEUS_URL") + "/api/v1/write"
  }
}

// =============================================================================
// LOKI LOG COLLECTION AND FORWARDING
// =============================================================================

// Local file discovery
local.file_match "local_files" {
  path_targets = [
    {__path__ = "/var/log/*.log", job = "system"},
    {__path__ = "/var/log/syslog", job = "system"},
    {__path__ = "/var/log/auth.log", job = "auth"},
  ]
}

// Scrape log files
loki.source.file "log_scrape" {
  targets    = local.file_match.local_files.targets
  forward_to = [loki.process.filter_logs.receiver]
  tail_from_end = true
}

// Filter non-essential logs
loki.process "filter_logs" {
  stage.drop {
    source = ""
    expression  = ".*Connection closed by authenticating user root"
    drop_counter_reason = "noisy"
  }
  
  stage.labels {
    values = {
      instance = env("HOSTNAME"),
      job = "system",
    }
  }
  
  forward_to = [loki.write.loki_service.receiver]
}

// Write logs to central Loki
loki.write "loki_service" {
  endpoint {
    url = env("LOKI_URL") + "/loki/api/v1/push"
  }
}

// Collect Docker container logs
loki.source.docker "container_logs" {
  host = "unix:///var/run/docker.sock"
  targets = [
    {__path__ = "/var/lib/docker/containers/*/*-json.log", job = "docker"},
  ]
  
  forward_to = [loki.process.add_labels.receiver]
}

// Add labels to container logs
loki.process "add_labels" {
  stage.labels {
    values = {
      instance = env("HOSTNAME"),
      job = "docker",
    }
  }
  
  forward_to = [loki.write.loki_service.receiver]
}
