server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  # Point to central Loki server - uses environment variables
  - url: ${LOKI_URL:-http://central-server:3100}/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          instance: ${HOSTNAME:-unknown}
          __path__: /var/log/*.log

  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
      - source_labels: ['__meta_docker_container_label_logging_driver']
        target_label: 'driver'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        regex: '.*'
        action: replace
        target_label: 'job'
        replacement: 'docker'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'instance'
        replacement: '${HOSTNAME:-unknown}'

  # Application logs
  - job_name: applications
    static_configs:
      - targets:
          - localhost
        labels:
          job: applications
          instance: ${HOSTNAME:-unknown}
          __path__: /var/log/apps/*.log

  # Auth logs
  - job_name: auth
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth
          instance: ${HOSTNAME:-unknown}
          __path__: /var/log/auth.log
